In [2]:
import sys
sys.path.insert(0, "../src")

import pandas as pd
from batch_contact_and_segment import run_batch_contact_and_segmentation

HAND_ROOT = "../outputs/hand_landmarks"
OBJ_ROOT  = "../outputs/object_detections"
OUT_ROOT  = "../outputs"  # will create outputs/contacts and outputs/segments inside

DIST_THRESH_PX = 25
MIN_LEN_FRAMES = 5
GAP_MERGE_FRAMES = 3

In [3]:
summary_df = run_batch_contact_and_segmentation(
    hand_root_dir=HAND_ROOT,
    obj_root_dir=OBJ_ROOT,
    out_root_dir=OUT_ROOT,
    dist_thresh_px=DIST_THRESH_PX,
    min_len_frames=MIN_LEN_FRAMES,
    gap_merge_frames=GAP_MERGE_FRAMES
)

summary_df.to_csv("../outputs/contact_segmentation_summary.csv", index=False)
summary_df.head(10)

Contact+Segmentation (videos): 100%|██████████| 10/10 [00:01<00:00,  5.12it/s]

,domain,video_stem,frames_total,contact_events,segments,contacts_csv,segments_csv,status
0,artificial_jewellery,video_20260404_114752,377,1747,4,../outputs/contacts/artificial_jewellery/video...,../outputs/segments/artificial_jewellery/video...,success
1,artificial_jewellery,video_20260404_115542,224,741,2,../outputs/contacts/artificial_jewellery/video...,../outputs/segments/artificial_jewellery/video...,success
2,artificial_jewellery,video_20260404_120254,79,270,1,../outputs/contacts/artificial_jewellery/video...,../outputs/segments/artificial_jewellery/video...,success
3,artificial_jewellery,video_20260404_121005,25,78,2,../outputs/contacts/artificial_jewellery/video...,../outputs/segments/artificial_jewellery/video...,success
4,artificial_jewellery,video_20260404_121903,427,633,20,../outputs/contacts/artificial_jewellery/video...,../outputs/segments/artificial_jewellery/video...,success
5,artificial_jewellery,video_20260404_122845,16,11,0,../outputs/contacts/artificial_jewellery/video...,../outputs/segments/artificial_jewellery/video...,success
6,artificial_jewellery,video_20260405_105612_edit,8,57,1,../outputs/contacts/artificial_jewellery/video...,../outputs/segments/artificial_jewellery/video...,success
7,home_cleaning,video_20260404_073018,0,0,0,NaN,NaN,skipped_empty_csv
8,home_cleaning,video_20260404_074030,3,7,0,../outputs/contacts/home_cleaning/video_202604...,../outputs/segments/home_cleaning/video_202604...,success
9,shop,video_20260405_163219_edit,22,53,1,../outputs/contacts/shop/video_20260405_163219...,../outputs/segments/shop/video_20260405_163219...,success

In [4]:
# pick a successful row
ok = summary_df[summary_df["status"]=="success"]
if len(ok):
    seg_path = ok.iloc[0]["segments_csv"]
    con_path = ok.iloc[0]["contacts_csv"]
    seg = pd.read_csv(seg_path)
    con = pd.read_csv(con_path) if con_path else pd.DataFrame()
    print("Segments:")
    display(seg.head(20))
    print("Contacts sample:")
    display(con.head(20))

Segments:

,domain,video_stem,start_frame,end_frame,duration_frames
0,artificial_jewellery,video_20260404_114752,90,4620,4531
1,artificial_jewellery,video_20260404_114752,4770,6750,1981
2,artificial_jewellery,video_20260404_114752,6960,7020,61
3,artificial_jewellery,video_20260404_114752,7530,12120,4591

Contacts sample:

,hand_id,handedness,object_label,object_source,object_conf,x1,y1,x2,y2,fingertips_inside,min_tip_dist_px,domain,video_stem,frame_id
0,0,Left,person,yolo,0.269119,530.223633,3.415512,1646.061035,689.861206,5,0.00000,artificial_jewellery,video_20260404_114752,0
1,1,Right,person,yolo,0.724315,1187.540161,6.240372,1917.281372,642.943604,5,0.00000,artificial_jewellery,video_20260404_114752,0
2,1,Right,person,yolo,0.269119,530.223633,3.415512,1646.061035,689.861206,5,0.00000,artificial_jewellery,video_20260404_114752,0
3,0,Left,person,yolo,0.461859,541.482056,2.328049,1807.316895,594.507690,5,0.00000,artificial_jewellery,video_20260404_114752,30
4,0,Left,person,yolo,0.307261,524.707397,5.755188,1067.791992,534.140259,5,0.00000,artificial_jewellery,video_20260404_114752,30
5,0,Left,small_object_proposal,heuristic,1.000000,1009.000000,414.000000,1066.000000,434.000000,1,0.00000,artificial_jewellery,video_20260404_114752,30
6,1,Right,person,yolo,0.461859,541.482056,2.328049,1807.316895,594.507690,5,0.00000,artificial_jewellery,video_20260404_114752,30
7,1,Right,person,yolo,0.457482,1206.994629,4.933182,1865.696045,551.846252,4,0.00000,artificial_jewellery,video_20260404_114752,30
8,0,Left,person,yolo,0.409872,514.237976,5.812363,1059.505005,537.646362,5,0.00000,artificial_jewellery,video_20260404_114752,90
9,0,Left,person,yolo,0.323432,525.138245,2.159180,1836.152466,645.316284,5,0.00000,artificial_jewellery,video_20260404_114752,90
10,0,Left,dining table,yolo,0.312253,81.768860,370.088562,1914.522705,1062.821777,5,0.00000,artificial_jewellery,video_20260404_114752,90
11,1,Right,person,yolo,0.372683,1197.413574,5.945251,1832.826782,569.804382,4,0.00000,artificial_jewellery,video_20260404_114752,90
12,1,Right,person,yolo,0.323432,525.138245,2.159180,1836.152466,645.316284,5,0.00000,artificial_jewellery,video_20260404_114752,90
13,1,Right,dining table,yolo,0.312253,81.768860,370.088562,1914.522705,1062.821777,5,0.00000,artificial_jewellery,video_20260404_114752,90
14,1,Right,small_object_proposal,heuristic,1.000000,1112.000000,338.000000,1186.000000,395.000000,0,22.36068,artificial_jewellery,video_20260404_114752,90
15,0,Left,person,yolo,0.498744,512.459473,6.637756,1059.799072,556.037903,5,0.00000,artificial_jewellery,video_20260404_114752,120
16,0,Left,person,yolo,0.275898,543.548767,2.350296,1802.476074,689.309326,5,0.00000,artificial_jewellery,video_20260404_114752,120
17,1,Right,person,yolo,0.652902,1184.662720,7.058624,1903.845337,586.018311,4,0.00000,artificial_jewellery,video_20260404_114752,120
18,1,Right,person,yolo,0.275898,543.548767,2.350296,1802.476074,689.309326,5,0.00000,artificial_jewellery,video_20260404_114752,120
19,1,Right,small_object_proposal,heuristic,1.000000,1099.000000,405.000000,1175.000000,431.000000,0,20.00000,artificial_jewellery,video_20260404_114752,120